### ISSUE TITLE
segfault when opening windows

### ISSUE THREAD

**Issue by hrfee** [TheAvidDev/sway-borders#11]
### Please fill out the following:
- **Sway Version:** Latest git (1.5-93318d2)

- **Debug Log:**
[here](https://gist.github.com/hrfee/9f16efba38b791cd3ef051cc7c47097b). This was produced using the default configuration, but occurs using my own config too.

- **Configuration File:**
Default configuration file (`config.in` in this repo)

- **Stack Trace:**
[here](https://gist.github.com/hrfee/7c971377c529af2d7b3641b5e987298c).

- **Description:**
Running sway works fine, but when launching a terminal (Mod+Enter) or other applications through my launcher, it crashes and drops me back into the tty. Notably things that wouldn't have borders applied (swaybar, waybar, rofi-wayland, wofi, etc.) a.k.a programs using wlr-layer-shell (i believe) display fine.

**Comment by hrfee** [comment]
Just realised that setting `border_images` values in the config stops the crashing, so it seems it can't cope with not having images to show.

**Comment by TheAvidDev** [comment]
Thanks!
