### ISSUE TITLE
unfocused and unfocused_inactive borders are set to the same as the focused borders

### ISSUE THREAD

**Issue by chaitunya** [TheAvidDev/sway-borders#14]
The issue is demonstrated in this image:

![image](https://user-images.githubusercontent.com/13303232/95944577-57dc1600-0d9d-11eb-9333-94c7878ecfe9.png)

In my config, shown in the screenshot, I've set each border image (focused, unfocused, unfocused_inactive, and urgent) to different colors. As you can see, each of those files are different.

However, even though each of the border images are different, the border images for all borders are set to focused, regardless if they are actually focused.

**Comment by TheAvidDev** [comment]
Yep, this isn't implemented yet. See #6

**Comment by chaitunya** [comment]
Oops, I didn't see that.
